# Generated by Django 4.2.3 on 2023-07-27 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandoleiros', '0002_personagens_nascimento_personagens_signo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagens',
            name='nascimento',
            field=models.DateField(default=datetime.date(2023, 7, 27)),
        ),
    ]
