# Generated by Django 4.2.3 on 2023-07-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandoleiros', '0003_alter_personagens_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagens',
            name='signo',
            field=models.CharField(choices=[(1, 'Aquário'), (2, 'Peixes'), (3, 'Áries'), (4, 'Touro'), (5, 'Gêmeos'), (6, 'Câncer'), (7, 'Leão'), (8, 'Virgem'), (9, 'Libra'), (10, 'Escorpião'), (11, 'Sagitário'), (12, 'Capricórnio')], default=1, max_length=20),
        ),
    ]
